#!/usr/bin/env python3
"""
One-shot capture script: runs the pocket generator on involute.dxf, intercepts
calls to find_best_arc_distance where the convergence loop hits ITERATION_COUNT,
and writes each failure's inputs to a fixture module in this directory.

Run from the repo root:
    python3 tests/fixtures/capture_convergence_failures.py

The generated convergence_failure_N.py files are checked in as test fixtures.
Re-run this script only if the geometry or step size changes significantly.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import ezdxf
from shapely.wkt import dumps as wkt_dumps

import hsm_nibble.arc_fitter as arc_fitter_module
from hsm_nibble.arc_fitter import find_best_arc_distance as _real_find_best_arc_distance
from hsm_nibble.arc_fitter import ITERATION_COUNT
from hsm_nibble import dxf
from hsm_nibble import geometry

FIXTURE_DIR = os.path.dirname(os.path.abspath(__file__))
DXF_PATH = os.path.join(
    os.path.dirname(os.path.dirname(FIXTURE_DIR)),
    "test_cases", "involute.dxf"
)
OVERLAP = 3.2
WINDING = geometry.ArcDir.CW

_captured = []


def _capturing_find_best_arc_distance(
        voronoi_edge, start_distance, min_distance, step,
        winding_dir, calculated_area, last_circle,
        distance_from_geom, max_dist, controller):
    result = _real_find_best_arc_distance(
        voronoi_edge=voronoi_edge,
        start_distance=start_distance,
        min_distance=min_distance,
        step=step,
        winding_dir=winding_dir,
        calculated_area=calculated_area,
        last_circle=last_circle,
        distance_from_geom=distance_from_geom,
        max_dist=max_dist,
        controller=controller,
    )
    _, _, _, iteration_count, _ = result
    if iteration_count == ITERATION_COUNT:
        _captured.append(dict(
            voronoi_edge=voronoi_edge,
            start_distance=start_distance,
            min_distance=min_distance,
            step=step,
            winding_dir=winding_dir,
            calculated_area=calculated_area,
            last_circle=last_circle,
            max_dist=max_dist,
            # distance_from_geom is reconstructed from pocket_polygon at test time
            _distance_from_geom=distance_from_geom,
        ))
    return result


def _point_wkt(pt):
    if pt is None:
        return None
    return wkt_dumps(pt)


def _arcdata_to_dict(arc):
    if arc is None:
        return None
    return dict(
        origin_wkt=wkt_dumps(arc.origin),
        radius=arc.radius,
        start_wkt=_point_wkt(arc.start),
        end_wkt=_point_wkt(arc.end),
        start_angle=arc.start_angle,
        span_angle=arc.span_angle,
        winding_dir=arc.winding_dir.name if arc.winding_dir else None,
        path_wkt=wkt_dumps(arc.path),
        debug=arc.debug,
    )


def _write_fixture(index, capture):
    # Recover the pocket polygon from the distance_from_geom closure.
    # VoronoiCenters.distance_from_geom is: min(max_dist, polygon.boundary.distance(pt))
    # We capture distance_from_geom and test a known point to find the polygon.
    # Instead, we probe the __self__ attribute if it's a bound method.
    dfg = capture["_distance_from_geom"]
    if hasattr(dfg, "__self__"):
        pocket_polygon_wkt = wkt_dumps(dfg.__self__.polygon)
    else:
        pocket_polygon_wkt = None  # fallback — shouldn't happen with VoronoiCenters

    last_circle_dict = _arcdata_to_dict(capture["last_circle"])

    lines = [
        '"""',
        f'Convergence failure fixture {index}.',
        'Generated by tests/fixtures/capture_convergence_failures.py.',
        'Re-generate if pocket geometry or step size changes.',
        '"""',
        '',
        f'VORONOI_EDGE_WKT = {wkt_dumps(capture["voronoi_edge"])!r}',
        f'START_DISTANCE = {capture["start_distance"]!r}',
        f'MIN_DISTANCE = {capture["min_distance"]!r}',
        f'STEP = {capture["step"]!r}',
        f'MAX_DIST = {capture["max_dist"]!r}',
        f'WINDING_DIR = {capture["winding_dir"].name!r}',
        f'CALCULATED_AREA_WKT = {wkt_dumps(capture["calculated_area"])!r}',
        f'POCKET_POLYGON_WKT = {pocket_polygon_wkt!r}',
        '',
    ]

    if last_circle_dict is None:
        lines.append('LAST_CIRCLE = None')
    else:
        lines.append('LAST_CIRCLE = {')
        for k, v in last_circle_dict.items():
            lines.append(f'    {k!r}: {v!r},')
        lines.append('}')

    path = os.path.join(FIXTURE_DIR, f"convergence_failure_{index}.py")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}")


if __name__ == "__main__":
    # Monkey-patch the function in arc_fitter and in path_planner (which imported it).
    import hsm_nibble.path_planner as path_planner_module
    arc_fitter_module.find_best_arc_distance = _capturing_find_best_arc_distance
    path_planner_module.find_best_arc_distance = _capturing_find_best_arc_distance

    dxf_data = ezdxf.readfile(DXF_PATH)
    modelspace = dxf_data.modelspace()
    shape = dxf.dxf_to_polygon(modelspace)
    geometry.Pocket(shape, OVERLAP, WINDING, generate=False, debug=True)

    print(f"\nCaptured {len(_captured)} convergence failure(s).")
    for i, capture in enumerate(_captured):
        _write_fixture(i, capture)
